### ISSUE TITLE
Set up Nose tests

### ISSUE THREAD

**Issue by AaronParsons** [HERA-Team/hera_gpu#2]
Once we merge in branch median_filter, we will have unit tests in hera_gpu/tests, and we'd like to have those run automagically.

**Comment by AaronParsons** [comment]
But... I'm just realizing that it's hard to run unit tests on GPU code without a GPU.

**Comment by plaplant** [comment]
After a brief review of online discussion (like [here](https://github.com/travis-ci/travis-ci/issues/5911)), it seems that travis does not support GPU instances, nor does it plan to in the near future. Also, due to the fact that we're using CUDA and not OpenCL, there does not seem to be a viable emulator available. I could keep tabs on this issue, but we might be limited to CPU-only unit testing for the foreseeable future.
